2020-12-01 10:52:11,788 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2020-12-01 10:52:16,530 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2020-12-01 10:52:57,945 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2020-12-01 11:00:36,464 DEBUG - (nikko.aratan) - Successfully loaded and updated table
2020-12-01 11:08:49,279 DEBUG - (adrian.chong) - Successfully loaded and updated table
2020-12-01 11:29:51,793 DEBUG - starting thread (client mode): 0x1ea5f810L
2020-12-01 11:29:51,794 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.6.0
2020-12-01 11:29:51,815 DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2020-12-01 11:29:51,816 INFO - Connected (version 2.0, client OpenSSH_7.4)
2020-12-01 11:29:51,825 DEBUG - kex algos:[u'curve25519-sha256', u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group16-sha512', u'diffie-hellman-group18-sha512', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha256', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'aes128-cbc', u'aes192-cbc', u'aes256-cbc', u'blowfish-cbc', u'cast128-cbc', u'3des-cbc'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
2020-12-01 11:29:51,825 DEBUG - Kex agreed: curve25519-sha256@libssh.org
2020-12-01 11:29:51,825 DEBUG - HostKey agreed: ssh-ed25519
2020-12-01 11:29:51,825 DEBUG - Cipher agreed: aes128-ctr
2020-12-01 11:29:51,825 DEBUG - MAC agreed: hmac-sha2-256
2020-12-01 11:29:51,825 DEBUG - Compression agreed: none
2020-12-01 11:29:51,879 DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2020-12-01 11:29:51,880 DEBUG - Switch to new keys ...
2020-12-01 11:29:51,894 DEBUG - Adding ssh-ed25519 host key for [103.218.2.148]:28032: fb679dcdfda01a6424c0563de3f822e1
2020-12-01 11:29:51,896 DEBUG - Trying discovered key f1e2a20412f7e99b7abdb041b22f15e1 in /root/.ssh/id_rsa
2020-12-01 11:29:51,926 DEBUG - userauth is OK
2020-12-01 11:29:56,987 INFO - Authentication (publickey) successful!
2020-12-01 11:29:57,000 DEBUG - [chan 0] Max packet in: 32768 bytes
2020-12-01 11:29:57,005 DEBUG - Received global request "hostkeys-00@openssh.com"
2020-12-01 11:29:57,005 DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2020-12-01 11:29:57,005 DEBUG - Debug msg: Adding to environment: NAME=argus
2020-12-01 11:29:57,049 DEBUG - [chan 0] Max packet out: 32768 bytes
2020-12-01 11:29:57,049 DEBUG - Secsh channel 0 opened.
2020-12-01 11:29:57,071 DEBUG - [chan 0] Sesch channel 0 request ok
2020-12-01 11:29:57,077 DEBUG - [chan 0] Sesch channel 0 request ok
2020-12-01 11:29:57,078 DEBUG - [chan 1] Max packet in: 32768 bytes
2020-12-01 11:29:57,083 DEBUG - [chan 1] Max packet out: 32768 bytes
2020-12-01 11:29:57,083 DEBUG - Secsh channel 1 opened.
2020-12-01 11:29:57,093 DEBUG - [chan 1] Sesch channel 1 request ok
2020-12-01 11:30:10,438 DEBUG - [chan 2] Max packet in: 32768 bytes
2020-12-01 11:30:10,439 DEBUG - [chan 1] EOF received (1)
2020-12-01 11:30:10,440 DEBUG - [chan 1] EOF sent (1)
2020-12-01 11:30:10,443 DEBUG - [chan 2] Max packet out: 32768 bytes
2020-12-01 11:30:10,443 DEBUG - Secsh channel 2 opened.
2020-12-01 11:30:10,496 DEBUG - [chan 2] Sesch channel 2 request ok
2020-12-01 11:30:10,530 DEBUG - [chan 2] EOF received (2)
2020-12-01 11:30:10,530 DEBUG - [chan 2] EOF sent (2)
2020-12-01 11:30:10,531 DEBUG - EOF in transport thread
2020-12-01 15:53:17,724 ERROR - Internal Server Error: /esync/acc-midpay_nginx/generate/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/app/argus_final/app/argus/argus/mixins.py", line 14, in dispatch
    return super(GENERIC_PERMISSION_MIXIN, self).dispatch(request, *args, **kwargs)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/argus_final/app/argus/esync/views.py", line 287, in post
    nonstandard_esync_log(hostgroup, request.user.username, [result[1]],activity_type='CREATE')
  File "/app/argus_final/app/argus/esync/lib/esync_logger.py", line 20, in nonstandard_esync_log
    f.write(i)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 342-348: ordinal not in range(128)
