2020-11-27 17:39:20,234 DEBUG - (aaron.navarro) - Successfully loaded and updated table
2020-11-27 17:39:22,079 INFO - "GET /ssl-checker/ HTTP/1.0" 200 2497614
2020-11-27 17:39:26,355 ERROR - Internal Server Error: /cdn-checker/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/cdn/views.py", line 43, in pageDisplay
    return render(request, 'cdn-domain/home.html', args)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 50, in __iter__
    compiler = queryset.query.get_compiler(using=db)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 255, in get_compiler
    connection = connections[using]
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/utils.py", line 208, in __getitem__
    self.ensure_defaults(alias)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/utils.py", line 178, in ensure_defaults
    raise ConnectionDoesNotExist("The connection %s doesn't exist" % alias)
ConnectionDoesNotExist: The connection cdnDB doesn't exist
2020-11-27 17:39:26,692 ERROR - "GET /cdn-checker/ HTTP/1.0" 500 179571
2020-11-27 17:49:51,703 DEBUG - (aaron.navarro) - Successfully loaded and updated table
2020-11-27 17:49:53,358 INFO - "GET /ssl-checker/ HTTP/1.0" 200 2497614
2020-11-27 17:49:55,763 WARNING - Not Found: /favicon.ico
2020-11-27 17:49:55,764 WARNING - "GET /favicon.ico HTTP/1.0" 404 4613
2020-11-27 17:50:03,216 ERROR - Internal Server Error: /cdn-checker/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/cdn/views.py", line 43, in pageDisplay
    return render(request, 'cdn-domain/home.html', args)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'argus_v2.cdn_cdndomain' doesn't exist")
2020-11-27 17:50:03,449 ERROR - "GET /cdn-checker/ HTTP/1.0" 500 173831
2020-11-27 17:53:28,398 DEBUG - (aaron.navarro) - Successfully loaded and updated table
2020-11-27 17:53:30,029 INFO - "GET /ssl-checker/ HTTP/1.0" 200 2497614
2020-11-27 17:53:35,463 ERROR - Internal Server Error: /cdn-checker/
Traceback (most recent call last):
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/argus_final/app/argus/cdn/views.py", line 43, in pageDisplay
    return render(request, 'cdn-domain/home.html', args)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/template/defaulttags.py", line 173, in render
    len_values = len(values)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/app/argus_final/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
ProgrammingError: (1146, "Table 'argus_v2.cdn_cdndomain' doesn't exist")
2020-11-27 17:53:35,674 ERROR - "GET /cdn-checker/ HTTP/1.0" 500 173832
